name: Run Selenium Test

on:
  push:
    branches: ["master"]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
           java-version: "18"
           cache: maven
           distribution: "temurin"
      - uses: browser-actions/setup-chrome@latest
      - run: mvn clean test